<h1>Anexo 05c: Predicción Modelos Kaggle en Python en GCP<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Carga-Módulos" data-toc-modified-id="Carga-Módulos-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Carga Módulos</a></span></li><li><span><a href="#Carga-Data-Sets" data-toc-modified-id="Carga-Data-Sets-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Carga Data Sets</a></span></li><li><span><a href="#Modelos-Individuales" data-toc-modified-id="Modelos-Individuales-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Modelos Individuales</a></span><ul class="toc-item"><li><span><a href="#Ridge-Regression" data-toc-modified-id="Ridge-Regression-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Ridge Regression</a></span></li><li><span><a href="#Lasso-Regression" data-toc-modified-id="Lasso-Regression-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Lasso Regression</a></span></li><li><span><a href="#ElasticNet-Regression" data-toc-modified-id="ElasticNet-Regression-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>ElasticNet Regression</a></span></li><li><span><a href="#Support-Vector-Regressor-Linear" data-toc-modified-id="Support-Vector-Regressor-Linear-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Support Vector Regressor Linear</a></span></li><li><span><a href="#Gradient-Boosting-Regressor" data-toc-modified-id="Gradient-Boosting-Regressor-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Gradient Boosting Regressor</a></span></li></ul></li><li><span><a href="#Ensamblados" data-toc-modified-id="Ensamblados-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Ensamblados</a></span><ul class="toc-item"><li><span><a href="#Ensamblado-1" data-toc-modified-id="Ensamblado-1-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Ensamblado 1</a></span></li><li><span><a href="#Ensamblado-2" data-toc-modified-id="Ensamblado-2-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Ensamblado 2</a></span></li><li><span><a href="#Ensamblado-3" data-toc-modified-id="Ensamblado-3-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Ensamblado 3</a></span></li><li><span><a href="#Ensamblado-4" data-toc-modified-id="Ensamblado-4-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Ensamblado 4</a></span></li></ul></li><li><span><a href="#Ranking-Kaggle" data-toc-modified-id="Ranking-Kaggle-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Ranking Kaggle</a></span></li></ul></div>

En este notebook se definen los mejores modelos obtenidos a partir de los algoritmos anteriores, con **Python**, y se procede a la predicción de datos test, para posteriormente subirlos a la **plataforma Kaggle**

# Carga Módulos

In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

import json 

# Carga Data Sets

In [2]:
train_prep = pd.read_csv('X_train_embedd.csv', sep = ',')
test_prep = pd.read_csv('X_test_embedd.csv', sep = ',')

# Modelos Individuales

In [3]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.ensemble import GradientBoostingRegressor, VotingRegressor
from sklearn.svm import SVR

## Ridge Regression

In [4]:
ridge = Ridge(alpha=0.2012, copy_X=True, fit_intercept=True, max_iter=None,
              normalize=False, random_state=12345, solver='auto', tol=0.001).\
              fit(train_prep.iloc[:, 1:], train_prep.SalePrice)

In [5]:
ridge_59 = np.expm1(ridge.predict(test_prep))
ridge_59

array([116872.33705944, 164318.24588238, 182420.23713635, ...,
       177901.34644969, 115267.39167164, 220067.36533173])

In [6]:
pd.DataFrame({"Id" :list(range(1461, 2920)), "SalePrice": ridge_59}).\
              to_csv("./predicciones/ridge_pred.csv", header=True, index=False)

## Lasso Regression

In [7]:
lasso = Lasso(alpha=0.0021018018018018015, copy_X=True, fit_intercept=True,
              max_iter=10000000.0, normalize=False, positive=False, precompute=False,
              random_state=12345, selection='cyclic', tol=0.0001, warm_start=False).\
              fit(train_prep.iloc[:, 1:], train_prep.SalePrice)

In [8]:
lasso_59 = np.expm1(lasso.predict(test_prep))
lasso_59

array([115136.45921974, 164951.40088002, 179640.30070454, ...,
       181986.38706238, 114976.77316276, 220820.40802794])

In [9]:
pd.DataFrame({"Id" :list(range(1461, 2920)), "SalePrice": lasso_59}).\
              to_csv("./predicciones/lasso_pred.csv", header=True, index=False)

## ElasticNet Regression

In [10]:
elasticnet = ElasticNet(alpha=0.0001, copy_X=True, fit_intercept=True,
                        l1_ratio=0.042, max_iter=10000000.0, normalize=False,
                        positive=False, precompute=False, random_state=12345,
                        selection='cyclic', tol=0.0001, warm_start=False).\
                        fit(train_prep.iloc[:, 1:], train_prep.SalePrice)

In [11]:
elasticnet_59 = np.expm1(elasticnet.predict(test_prep))
elasticnet_59

array([116704.00524468, 164366.23938847, 182448.08070823, ...,
       177866.25516319, 115285.35383189, 220036.22683633])

In [12]:
pd.DataFrame({"Id" :list(range(1461, 2920)), "SalePrice": elasticnet_59}).\
              to_csv("./predicciones/elasticnet_pred.csv", header=True, index=False)

## Support Vector Regressor Linear

In [13]:
SVRL = SVR(C=0.94197, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
           gamma='auto_deprecated', kernel='linear', max_iter=-1, shrinking=True,
           tol=0.001, verbose=False).fit(train_prep.iloc[:, 1:], train_prep.SalePrice)

In [14]:
SVRL_59 = np.expm1(SVRL.predict(test_prep))
SVRL_59

array([115208.52268944, 166072.99284489, 181277.90642415, ...,
       174974.93500221, 115406.0977877 , 217746.59042013])

In [15]:
pd.DataFrame({"Id" :list(range(1461, 2920)), "SalePrice": SVRL_59}).\
              to_csv("./predicciones/SVRL_pred.csv", header=True, index=False)

## Gradient Boosting Regressor

In [16]:
gbm = GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                                learning_rate=0.01, loss='ls', max_depth=5,
                                max_features='sqrt', max_leaf_nodes=None,
                                min_impurity_decrease=0.0, min_impurity_split=None,
                                min_samples_leaf=1, min_samples_split=2,
                                min_weight_fraction_leaf=0.0, n_estimators=900,
                                n_iter_no_change=None, presort='auto',
                                random_state=12345, subsample=1.0, tol=0.0001,
                                validation_fraction=0.1, verbose=0, warm_start=False).\
                                fit(train_prep.iloc[:, 1:], train_prep.SalePrice)

In [17]:
gbm_59 = np.expm1(gbm.predict(test_prep))
gbm_59

array([123831.80709561, 166889.57689913, 180367.97928288, ...,
       167197.71726003, 115908.35920477, 207767.35353171])

In [18]:
pd.DataFrame({"Id" :list(range(1461, 2920)), "SalePrice": gbm_59}).\
              to_csv("./predicciones/gbm_pred.csv", header=True, index=False)

# Ensamblados

## Ensamblado 1

In [19]:
ens1 = [("Lasso", lasso), 
        ("Ridge", ridge)]

weights1 = [0.5, 0.5]

In [20]:
ensemb1_59 = np.expm1(VotingRegressor(ens1, weights1, n_jobs=-1).\
                                   fit(train_prep.iloc[:, 1:], train_prep.SalePrice).\
                                   predict(test_prep))
ensemb1_59

array([116001.15118503, 164634.51900818, 181024.93271492, ...,
       179932.27425089, 115121.99071193, 220443.5651291 ])

In [21]:
pd.DataFrame({"Id" :list(range(1461, 2920)), "SalePrice": ensemb1_59}).\
              to_csv("./predicciones/ensemb1_pred.csv", header=True, index=False)

## Ensamblado 2

In [22]:
ens2 = [("Lasso", lasso), 
        ("Ridge", ridge), 
        ("Elasticnet", elasticnet)]

weights2 = [0.2, 0.2, 0.6]

In [23]:
ensemb2_59 = np.expm1(VotingRegressor(ens2, weights2, n_jobs=-1).\
                                   fit(train_prep.iloc[:, 1:], train_prep.SalePrice).\
                                   predict(test_prep))
ensemb2_59

array([116422.35403157, 164473.49873584, 181877.4838321 , ...,
       178689.8007604 , 115219.98078423, 220199.07175372])

In [24]:
pd.DataFrame({"Id" :list(range(1461, 2920)), "SalePrice": ensemb2_59}).\
              to_csv("./predicciones/ensemb2_pred.csv", header=True, index=False)

## Ensamblado 3

In [25]:
ens3 = [("Lasso", lasso), 
        ("Ridge", ridge), 
        ("Elasticnet", elasticnet),
        ("SVRL", SVRL)]

weights3 = [0.2, 0.2, 0.4, 0.2]

In [26]:
ensemb3_59 = np.expm1(VotingRegressor(ens3, weights3, n_jobs=-1).\
                                   fit(train_prep.iloc[:, 1:], train_prep.SalePrice).\
                                   predict(test_prep))
ensemb3_59

array([116122.43810853, 164813.6622244 , 181643.58005511, ...,
       178105.04463726, 115244.10577713, 219738.88614381])

In [27]:
pd.DataFrame({"Id" :list(range(1461, 2920)), "SalePrice": ensemb3_59}).\
              to_csv("./predicciones/ensemb3_pred.csv", header=True, index=False)

## Ensamblado 4

In [28]:
ens4 = [("Lasso", lasso), 
        ("Ridge", ridge), 
        ("Elasticnet", elasticnet),
        ("SVRL", SVRL),
        ("Gbm", gbm)]

weights4 = [0.2, 0.2, 0.2, 0.2, 0.2]

In [29]:
ensemb4_59 = np.expm1(VotingRegressor(ens4, weights4, n_jobs=-1).\
                                   fit(train_prep.iloc[:, 1:], train_prep.SalePrice).\
                                   predict(test_prep))
ensemb4_59

array([117507.4594716 , 165316.62433406, 181227.49231433, ...,
       175915.28564239, 115368.39390023, 217231.87112773])

In [30]:
pd.DataFrame({"Id" :list(range(1461, 2920)), "SalePrice": ensemb4_59}).\
              to_csv("./predicciones/ensemb4_pred.csv", header=True, index=False)